In [3]:
import numpy as np
list_ = [ '1', '2', '3' , '4' , '5' ]
array_list = np.array(object = list_)

# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [4]:
print(type(list_))

<class 'list'>


In [6]:
print(type(array_list))

<class 'numpy.ndarray'>


# Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [8]:
print("Data types in list_:")
for element in list_:
    print(type(element))

# Printing data types of each element in arra_list
print("\nData types in arra_list:")
for element in array_list:
    print(type(element))

Data types in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types in arra_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


# Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.
Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [9]:
array_list = np.array(object = list_, dtype = int)

In [10]:
'Yes, there will be a difference in the data type of the elements present in list_ and arra_list after the conversion. When you convert the list_ to a numpy array with dtype=int, all elements of the resulting array will be of type int. Elements that cannot be converted to integers will cause an error during this conversion.'

'Yes, there will be a difference in the data type of the elements present in list_ and arra_list after the conversion. When you convert the list_ to a numpy array with dtype=int, all elements of the resulting array will be of type int. Elements that cannot be converted to integers will cause an error during this conversion.'

In [13]:
# Printing data types of each element in list_
print("Data types in list_:")
for element in list_:
    print(type(element))

# Printing data types of each element in arra_list if conversion is successful
if 'arra_list' in locals():
    print("\nData types in arra_list:")
    for element in array_list:
        print(type(element))


Data types in list_:
<class 'str'>
<class 'int'>
<class 'float'>
<class 'bool'>


# Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [14]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [15]:
shape = num_array.shape
size = num_array.size

# Printing the results
print(f"Shape of num_array: {shape}")
print(f"Size of num_array: {size}")

Shape of num_array: (2, 3)
Size of num_array: 6


# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [17]:
zero_matrix=np.zeros((3,3))
print(zero_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [18]:
id_matrix=np.eye(5)
print(id_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
