# 1. What are the different data structures used in TensorFlow? Give some examples.

In [ ]:
Tensors: The central unit of data in TensorFlow, representing multi-dimensional arrays. They are similar to NumPy arrays but can run on GPUs.

Variables: These are special types of tensors used to maintain state across multiple runs of a computation graph. Variables can be updated during training.

Constants: Immutable tensors whose values cannot be changed after initialization.

SparseTensors: Efficiently represent and manipulate sparse data, where most elements are zeros.

Dataset: Used to represent a sequence of elements that can be processed in parallel or sequentially.

# 2. How does the TensorFlow constant differ from a TensorFlow variable?  

In [ ]:
A constant is a fixed value tensor that cannot be modified once it is created. It's used for fixed values that do not change during the execution of a program.

A variable is a mutable tensor whose value can be changed. It's typically used to store and update parameters during training.

In [3]:
import tensorflow as tf



In [5]:
a = tf.constant(5)
print("TensorFlow Constant:", a)

TensorFlow Constant: tf.Tensor(5, shape=(), dtype=int32)


In [9]:
b = tf.Variable(5)
print("Initial Variable:", b)

Initial Variable: <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=5>


In [11]:
b.assign(10)
print("Updated Variable:", b)

Updated Variable: <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10>


In [13]:
b.shape

TensorShape([])

# 3. Describe the process of matrix addition, multiplication, and element-wise operations in TensorFlow.

In [18]:
Matrix Addition: Adding two matrices of the same dimensions element-wise.
Matrix Multiplication: Performing the dot product between rows and columns of matrices.
Element-wise Operations: Operations performed on each element independently.

SyntaxError: invalid syntax (3118728827.py, line 1)

In [22]:
matrix1 = tf.constant([[1, 2], [3, 4]])
matrix2 = tf.constant([[5, 6], [7, 8]])
add_result = tf.add(matrix1, matrix2)
print(add_result)

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)


In [24]:
mul_result = tf.matmul(matrix1, matrix2)
print(mul_result)

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [26]:
elementwise_result = tf.multiply(matrix1, matrix2)
print(elementwise_result)

tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)


# Task 1: Creating and Manipulating Matrices 

 Create a normal matrix A with dimensions 2x2, using TensorFlow's random_normal function. Display the
values of matrix A

In [55]:
A=tf.random.normal([3,3])
print(a)

tf.Tensor(
[[-0.18122442  0.9003161 ]
 [-0.13341819  2.6116493 ]], shape=(2, 2), dtype=float32)


Cc Create a Gaussian matrix B with dimensions x, using TensorFlow's truncated_normal function. Display
the values of matrix B

In [41]:
B=tf.random.truncated_normal([4,4])
print(B)

tf.Tensor(
[[ 0.82329375  1.2041289   0.28913558  0.55604875]
 [ 0.26505935  0.11157151  1.267173    0.45559236]
 [-1.8791251   0.21743351 -0.5325515   0.7122137 ]
 [-0.16637169 -0.85146916 -0.42077     0.61200815]], shape=(4, 4), dtype=float32)


 Create a matrix C with dimensions 2x2, where the values are drawn from a normal distribution with a
mean of 2 and a standard deviation of 0.x, using TensorFlow's random.normal function. Display the values
of matrix C

In [46]:
C = tf.random.normal([2, 2], mean=3, stddev=0.5)
print( C)

tf.Tensor(
[[2.84987   3.1598444]
 [3.0034134 3.816002 ]], shape=(2, 2), dtype=float32)


4. Perform matrix addition between matrix A and matrix B, and store the result in matrix Dc
5. wc Perform matrix multiplication between matrix C and matrix D, and store the result in matrix E.

In [61]:
D = tf.add(A, B_add)
print(D)

Matrix D (A + B):
 tf.Tensor(
[[ 0.73280215 -0.61079353 -2.327613  ]
 [-0.20246828  0.3821621  -1.7278508 ]
 [-1.2922593   1.5225441   0.35556626]], shape=(3, 3), dtype=float32)


In [65]:
# Matrix multiplication (ensure D and C have compatible dimensions)
C_mul = tf.random.normal([3, 3])  # Reshape C if needed for this operation

E = tf.matmul(C_mul, D)
print( E)


tf.Tensor(
[[-0.2339445   0.08033732  1.6788843 ]
 [-0.65201515  0.60681254  1.3289967 ]
 [-1.7855585   1.9297338   1.2575338 ]], shape=(3, 3), dtype=float32)


1. Create a matrix F with dimensions 2x2, initialized with random values using TensorFlow's random_uniform
functionc
2. Calculate the transpose of matrix F and store the result in matrix Gc
3. Calculate the elementDwise exponential of matrix F and store the result in matrix Hc
4. Create a matrix I by concatenating matrix F and matrix G horizontallyc
5. Create a matrix J by concatenating matrix F and matrix H vertically.

In [68]:
# Create matrix F
F = tf.random.uniform([3, 3], minval=0, maxval=10)
print(F)


tf.Tensor(
[[1.579653  7.664969  8.647965 ]
 [2.8597581 9.767597  6.810602 ]
 [4.1531887 5.9823227 6.603278 ]], shape=(3, 3), dtype=float32)


In [70]:
# Transpose of F
G = tf.transpose(F)
print("Matrix G (Transpose of F):\n", G)


Matrix G (Transpose of F):
 tf.Tensor(
[[1.579653  2.8597581 4.1531887]
 [7.664969  9.767597  5.9823227]
 [8.647965  6.810602  6.603278 ]], shape=(3, 3), dtype=float32)


In [72]:
# Transpose of F
G = tf.transpose(F)
print("Matrix G (Transpose of F):\n", G)

Matrix G (Transpose of F):
 tf.Tensor(
[[1.579653  2.8597581 4.1531887]
 [7.664969  9.767597  5.9823227]
 [8.647965  6.810602  6.603278 ]], shape=(3, 3), dtype=float32)


In [74]:
# Element-wise exponential
H = tf.exp(F)
print("Matrix H (Exponential of F):\n", H)


Matrix H (Exponential of F):
 tf.Tensor(
[[4.8532715e+00 2.1323267e+03 5.6985410e+03]
 [1.7457304e+01 1.7458766e+04 9.0741705e+02]
 [6.3636593e+01 3.9635992e+02 7.3750891e+02]], shape=(3, 3), dtype=float32)


In [76]:
# Horizontal concatenation
I = tf.concat([F, G], axis=1)
print("Matrix I (F concatenated with G):\n", I)

Matrix I (F concatenated with G):
 tf.Tensor(
[[1.579653  7.664969  8.647965  1.579653  2.8597581 4.1531887]
 [2.8597581 9.767597  6.810602  7.664969  9.767597  5.9823227]
 [4.1531887 5.9823227 6.603278  8.647965  6.810602  6.603278 ]], shape=(3, 6), dtype=float32)


In [78]:
# Vertical concatenation
J = tf.concat([F, H], axis=0)
print("Matrix J (F concatenated with H):\n", J)


Matrix J (F concatenated with H):
 tf.Tensor(
[[1.5796530e+00 7.6649690e+00 8.6479654e+00]
 [2.8597581e+00 9.7675972e+00 6.8106022e+00]
 [4.1531887e+00 5.9823227e+00 6.6032782e+00]
 [4.8532715e+00 2.1323267e+03 5.6985410e+03]
 [1.7457304e+01 1.7458766e+04 9.0741705e+02]
 [6.3636593e+01 3.9635992e+02 7.3750891e+02]], shape=(6, 3), dtype=float32)
